import type { Project } from "@/types/api";

export const PROJECTS: Project[] = [
  {
    slug: "belt",
    title: "BELT",
    summary:
      "A cross-platform CLI that wraps Factorio benchmarking and turns save runs into reports, charts, and comparable data.",
    image: null,
    githubUrl: "https://github.com/florishafkenscheid/belt",
    liveUrl: null,
    year: 2025,
    status: "archived",
    tags: ["Rust", "CLI", "Factorio"],
    order: 1,
    narrative: {
      what: "BELT is a Rust command-line tool for running Factorio benchmarks across single saves or whole save directories, with pattern filtering, configurable ticks and runs, and generated CSV, Markdown, and SVG output.",
      why: "Factorio's built-in benchmark command is powerful but awkward to run repeatedly when comparing large saves, mods, or engine-heavy builds. BELT makes that workflow repeatable and readable.",
      how: "It discovers Factorio installs, runs benchmark and sanitize jobs, processes verbose metrics, and renders templated output with smoothing and downsampling so large result sets stay useful instead of turning into raw log archaeology.",
    },
  },
  {
    slug: "sharpfish",
    title: "Sharpfish",
    summary: "A C# library for talking to UCI-compatible chess engines.",
    image: null,
    githubUrl: "https://github.com/florishafkenscheid/Sharpfish",
    liveUrl: null,
    year: 2023,
    status: "shipped",
    tags: ["C#", "Chess", "UCI"],
    order: 2,
    narrative: {
      what: "Sharpfish is a C# library that manages the Universal Chess Interface protocol so an application can launch, configure, and communicate with UCI-compatible chess engines.",
      why: "Chess engine integrations tend to start as brittle process wrappers. Sharpfish keeps the protocol details in one place so tools can focus on positions, analysis, and results.",
      how: "It wraps engine process IO, sends UCI commands, parses engine responses, and exposes a typed surface for common operations like initialization, position setup, and search requests.",
    },
  },
  {
    slug: "worldmanager",
    title: "WorldManager",
    summary: "A backup-and-rollback layer for self-hosted Minecraft worlds, with snapshot diffing.",
    image: null,
    githubUrl: "https://github.com/florishafkenscheid/worldmanager",
    liveUrl: null,
    year: 2023,
    status: "archived",
    tags: ["Java", "Spigot", "Plugin"],
    order: 3,
    narrative: {
      what: "A Spigot plugin that snapshots the world on a schedule, lets ops roll back to any snapshot, and shows a chunk-level diff so you can see what actually changed.",
      why: "Friends griefing a build was costing me an evening every time. I wanted a one-command recovery and a record of who did what.",
      how: "Copy-on-write region files keep snapshots cheap. Diffs walk the chunk header tables, not the full block grid, so a snapshot/diff cycle finishes in seconds even on a 4GB world.",
    },
  },
  {
    slug: "pluginhider",
    title: "PluginHider",
    summary: "Hides the plugin list from probing players without breaking legitimate tab-complete.",
    image: null,
    githubUrl: "https://github.com/florishafkenscheid/pluginhider",
    liveUrl: null,
    year: 2023,
    status: "shipped",
    tags: ["Java", "Spigot", "Security"],
    order: 4,
    narrative: {
      what: "A Spigot plugin that intercepts /pl, /plugins, and tab-complete to return permission-gated responses instead of the full plugin roster.",
      why: "Knowing which plugins a server runs is half a recon for an exploit. Hiding the list is cheap insurance.",
      how: "Hooks the command dispatcher before Bukkit's default handler, and patches the tab-complete packet outbound so suggestions never leak. Negligible CPU cost; the packet is rewritten in place.",
    },
  },
  {
    slug: "lobby",
    title: "Lobby",
    summary:
      "A Java plugin that sends players to the WorldManager-owned lobby server when they log in.",
    image: null,
    githubUrl: "https://github.com/florishafkenscheid/lobby",
    liveUrl: null,
    year: 2024,
    status: "archived",
    tags: ["Java", "Spigot", "Plugin"],
    order: 5,
    narrative: {
      what: "Lobby is a Java server plugin that checks whether WorldManager owns a lobby server and sends players there when they join a server.",
      why: "It keeps the network entry point predictable: players land in the managed lobby instead of whichever backend server happened to receive the login.",
      how: "The plugin hooks into the player login flow, asks WorldManager for the configured lobby server, and redirects the player when that target is available.",
    },
  },
];
